public class DelaySubroutine extends javax.swing.JFrame {

    public DelaySubroutine() {
        initComponents();
        choiceHide(3);
    }

    Assembler o;
    public DelaySubroutine(Assembler o) {
        this.o=o;
        initComponents();
        choiceHide(3);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldDelayLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDelayTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDelayChoice = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabelMaximumDelay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTstate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxReg1 = new javax.swing.JComboBox();
        jComboBoxReg2 = new javax.swing.JComboBox();
        jComboBoxReg3 = new javax.swing.JComboBox();
        jComboBoxRegPair = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelMinimumDelay = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delay Subroutine");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(300, 150, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delay Subroutine Label : ");
        jLabel1.setName("jLabel1"); // NOI18N

        jTextFieldDelayLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDelayLabel.setName("jTextFieldDelayLabel"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Delay for  :");
        jLabel2.setName("jLabel2"); // NOI18N

        jTextFieldDelayTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDelayTime.setName("jTextFieldDelayTime"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ms");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(102, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Format of Subroutine  : ");
        jLabel4.setName("jLabel4"); // NOI18N

        jComboBoxDelayChoice.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBoxDelayChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delay Subroutine using One Register", "Delay Subroutine using Two Registers", "Delay Subroutine using Three Registers", "Delay Subroutine using Register Pair" }));
        jComboBoxDelayChoice.setSelectedIndex(3);
        jComboBoxDelayChoice.setName("jComboBoxDelayChoice"); // NOI18N
        jComboBoxDelayChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDelayChoiceActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("For this format maximum delay can be of ");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabelMaximumDelay.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelMaximumDelay.setForeground(new java.awt.Color(0, 0, 102));
        jLabelMaximumDelay.setText("100");
        jLabelMaximumDelay.setName("jLabelMaximumDelay"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("ms");
        jLabel7.setName("jLabel7"); // NOI18N

        jButton1.setText("OK");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("Time for 1 T-state : ");
        jLabel6.setName("jLabel6"); // NOI18N

        jTextFieldTstate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTstate.setText("320");
        jTextFieldTstate.setName("jTextFieldTstate"); // NOI18N
        jTextFieldTstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTstateActionPerformed(evt);
            }
        });
        jTextFieldTstate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTstateKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ns");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Registers used : ");
        jLabel9.setName("jLabel9"); // NOI18N

        jComboBoxReg1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "H", "L" }));
        jComboBoxReg1.setName("jComboBoxReg1"); // NOI18N

        jComboBoxReg2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "H", "L" }));
        jComboBoxReg2.setName("jComboBoxReg2"); // NOI18N

        jComboBoxReg3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "H", "L" }));
        jComboBoxReg3.setName("jComboBoxReg3"); // NOI18N

        jComboBoxRegPair.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B-C", "D-E", "H-L" }));
        jComboBoxRegPair.setName("jComboBoxRegPair"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("& minimum delay of ");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setForeground(new java.awt.Color(153, 0, 153));
        jLabel11.setText("ms ");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabelMinimumDelay.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelMinimumDelay.setForeground(new java.awt.Color(0, 0, 102));
        jLabelMinimumDelay.setText("100");
        jLabelMinimumDelay.setName("jLabelMinimumDelay"); // NOI18N

        jButton2.setText("Cancel");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDelayTime, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDelayChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTstate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(jTextFieldDelayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelMinimumDelay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxReg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxReg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxReg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRegPair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMaximumDelay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDelayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDelayTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxDelayChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxReg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxReg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxReg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRegPair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelMaximumDelay)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabelMinimumDelay)
                            .addComponent(jLabel11))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean check()
    {
         Float f=0f;
         boolean check=false;
        try{
            f=Float.valueOf(jTextFieldDelayTime.getText());
        if(f<Float.valueOf(jLabelMinimumDelay.getText()))Popup.show("It cannot be smaller than minimum value");
        else if(f>Float.valueOf(jLabelMaximumDelay.getText()))Popup.show("It cannot be larger than maximum value");
        else    check=true;
        }
        catch(Exception e){
            Popup.show("Invalid Number");
            jTextFieldDelayTime.setText("1");
        }
         return check;

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(check()){
        int choice=jComboBoxDelayChoice.getSelectedIndex();
        if(choice==0)delayReg1();
        else if(choice==1)delayReg2();
        else if(choice==2)delayReg3();
        else if(choice==3)delaySubRegPair();
        dispose();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxDelayChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDelayChoiceActionPerformed

        choiceHide(jComboBoxDelayChoice.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxDelayChoiceActionPerformed

    private void jTextFieldTstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTstateActionPerformed

    }//GEN-LAST:event_jTextFieldTstateActionPerformed

    private void jTextFieldTstateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTstateKeyReleased

        choiceHide(jComboBoxDelayChoice.getSelectedIndex());

    }//GEN-LAST:event_jTextFieldTstateKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void choiceHide(int choice)
    {
        int tState=0;
        try{
            tState=Integer.parseInt(jTextFieldTstate.getText());
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(tState));}
        jComboBoxReg1.setVisible(false);
        jComboBoxReg2.setVisible(false);
        jComboBoxReg3.setVisible(false);
        jComboBoxRegPair.setVisible(false);
        switch(choice){
            case 0:jComboBoxReg1.setVisible(true);
                   jComboBoxReg1.setSelectedIndex(1);
                   jLabelMinimumDelay.setText(String.valueOf((0.028*tState)/1000));
                   jLabelMaximumDelay.setText(String.valueOf((3.584*tState)/1000));
                    break;
            case 1:jComboBoxReg1.setVisible(true);
                   jComboBoxReg2.setVisible(true);
                   jComboBoxReg1.setSelectedIndex(1);
                   jComboBoxReg2.setSelectedIndex(2);
                   jLabelMinimumDelay.setText(String.valueOf((0.046*tState)/1000));
                   jLabelMaximumDelay.setText(String.valueOf((914.954*tState)/1000));

                   break;
            case 2:jComboBoxReg1.setVisible(true);
                   jComboBoxReg2.setVisible(true);
                   jComboBoxReg3.setVisible(true);
                   jComboBoxReg1.setSelectedIndex(1);
                   jComboBoxReg2.setSelectedIndex(2);
                   jComboBoxReg3.setSelectedIndex(3);
                   jLabelMinimumDelay.setText(String.valueOf((0.064*tState)/1000));
                   jLabelMaximumDelay.setText(String.valueOf((233.314304*tState)));
                   break;
            case 3:jComboBoxRegPair.setVisible(true);
                   jLabelMinimumDelay.setText(String.valueOf((0.408*tState)/1000));
                   jLabelMaximumDelay.setText(String.valueOf((1.572857*tState)));
                   break;
            default:break;
        }
    }

    public String delaySubRegPair()
    {
        String s="";
        int tState=0;
        try{
            tState=Integer.parseInt(jTextFieldTstate.getText());
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(tState));}

        int TStates=0;
        try{
            TStates=(int) (Double.parseDouble(jTextFieldDelayTime.getText())*1000*1000);
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(TStates));}

        int count=((TStates/tState) - 17)/24;
        String space="\t   ";
        String D=jComboBoxRegPair.getItemAt(jComboBoxRegPair.getSelectedIndex()).toString();
        String E=String.valueOf(D.charAt(2));
        D=String.valueOf(D.charAt(0));
        s=jTextFieldDelayLabel.getText()+":";
        s=s+"\n"+space+"LXI "+D+","+o.engine.Dec2Hex(count);
        s=s+"\n"+jTextFieldDelayLabel.getText()+"Loop:\n"+space+"DCX "+D;
        s=s+"\n"+space+"MOV A,"+D;
        s=s+"\n"+space+"ORA "+E;
        s=s+"\n"+space+"JNZ "+jTextFieldDelayLabel.getText()+"Loop";
        s=s+"\n"+space+"RET";
        o.jTextAreaAssemblyLanguageEditor.setText(o.jTextAreaAssemblyLanguageEditor.getText()+s);
        o.textEditor.colorEditor();
        return s;
    }

    public String delayReg1()
    {
        String s="";
        int tState=0;
        try{
            tState=Integer.parseInt(jTextFieldTstate.getText());
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(tState));}

        int TStates=0;
        try{
            TStates=(int) (Double.parseDouble(jTextFieldDelayTime.getText())*1000*1000);
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(TStates));}

        int noTstate=(TStates/tState);
        int count=(noTstate/14)-1;
        String space="\t   ";
        String B=jComboBoxReg1.getItemAt(jComboBoxReg1.getSelectedIndex()).toString();
        s=jTextFieldDelayLabel.getText()+":";
        s=s+"\n"+space+"MVI "+B+","+o.engine.Dec2Hex2digit(count);
        s=s+"\n"+jTextFieldDelayLabel.getText()+"Loop:\n"+space+"DCR "+B;
        s=s+"\n"+space+"JNZ "+jTextFieldDelayLabel.getText()+"Loop";
        s=s+"\n"+space+"RET";
        o.jTextAreaAssemblyLanguageEditor.setText(o.jTextAreaAssemblyLanguageEditor.getText()+s);
        o.textEditor.colorEditor();
        return s;
    }

    public int[] solveReg2(int tstates)
    {
        int present=0,x=0,y=0,a[]={0,0},past=0,px=0,py=0;
        for(x=0;x<256;x++)
        {
            for(y=0;y<256;y++)
            {
                present=14+18*x+14*x*y;  
                if(present/tstates>=1&&present/tstates<1.00002){
                    if(past==0)past=present;
                    if(past%tstates>=present%tstates)
                    {
                    past=present;px=x;py=y;
                    }
                }
            }
        }
         a[0]=px;a[1]=py;
        return a;
    }

    public String delayReg2()
    {
        String s="";
        int tState=0;
        try{
            tState=Integer.parseInt(jTextFieldTstate.getText());
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(tState));}

        int TStates=0;
        try{
            TStates=(int) (Double.parseDouble(jTextFieldDelayTime.getText())*1000*1000);
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(TStates));}

        int noTstate=(TStates/tState);
        int count[]=solveReg2(noTstate);
        String space="\t   ";
        String B=jComboBoxReg1.getItemAt(jComboBoxReg1.getSelectedIndex()).toString();
        String C=jComboBoxReg2.getItemAt(jComboBoxReg2.getSelectedIndex()).toString();
        s=jTextFieldDelayLabel.getText()+":";
        s=s+"\n"+space+"MVI "+B+","+o.engine.Dec2Hex2digit(count[0]);
        s=s+"\n"+jTextFieldDelayLabel.getText()+"Loop1:\n"+space+"MVI "+C+","+o.engine.Dec2Hex2digit(count[1]);
        s=s+"\n"+jTextFieldDelayLabel.getText()+"Loop2:\n"+space+"DCR "+C;
        s=s+"\n"+space+"JNZ "+jTextFieldDelayLabel.getText()+"Loop2";
        s=s+"\n"+space+"DCR "+B;
        s=s+"\n"+space+"JNZ "+jTextFieldDelayLabel.getText()+"Loop1";
        s=s+"\n"+space+"RET";
        o.jTextAreaAssemblyLanguageEditor.setText(o.jTextAreaAssemblyLanguageEditor.getText()+s);
        o.textEditor.colorEditor();
        return s;
    }

    public int[] solveReg3(long tstates)
    {
        long present=0,past=0;
        int x=0,y=0,z=0,a[]={0,0,0},px=0,py=0,pz=0;
        for(x=0;x<256;x++)
        {
            for(y=0;y<256;y++)
            {
               for(z=0;z<256;z++)
                {
                 present=14+18*x+18*x*y+14*x*y*z;
                 if(present/tstates>=1&&present/tstates<1.00002){
                     if(past==0)past=present;
                    if(past%tstates>=present%tstates)
                    {
                        past=present;px=x;py=y;pz=z;
                    }
                 }
                }
            }
        }
         a[0]=px;a[1]=py;a[2]=pz;
        return a;
    }

    public String delayReg3()
    {
        String s="";
        long tState=0;
        try{
            tState=Integer.parseInt(jTextFieldTstate.getText());
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(tState));}

        long TStates=0;
        try{
            TStates=(long) (Double.parseDouble(jTextFieldDelayTime.getText())*1000*1000);
        }catch(Exception e){jTextFieldTstate.setText(String.valueOf(TStates));}

        long noTstate=(TStates/tState);
        int count[]=solveReg3(noTstate);
        String space="\t   ";
        String B=jComboBoxReg1.getItemAt(jComboBoxReg1.getSelectedIndex()).toString();
        String C=jComboBoxReg2.getItemAt(jComboBoxReg2.getSelectedIndex()).toString();
        String D=jComboBoxReg3.getItemAt(jComboBoxReg3.getSelectedIndex()).toString();
        s=jTextFieldDelayLabel.getText()+":";
        s=s+"\n"+space+"MVI "+B+","+o.engine.Dec2Hex2digit(count[0]);
        s=s+"\n"+jTextFieldDelayLabel.getText()+"Loop1:\n"+space+"MVI "+C+","+o.engine.Dec2Hex2digit(count[1]);
        s=s+"\n"+jTextFieldDelayLabel.getText()+"Loop2:\n"+space+"MVI "+D+","+o.engine.Dec2Hex2digit(count[2]);
        s=s+"\n"+jTextFieldDelayLabel.getText()+"Loop3:\n"+space+"DCR "+D;
        s=s+"\n"+space+"JNZ "+jTextFieldDelayLabel.getText()+"Loop3";
        s=s+"\n"+space+"DCR "+C;
        s=s+"\n"+space+"JNZ "+jTextFieldDelayLabel.getText()+"Loop2";
        s=s+"\n"+space+"DCR "+B;
        s=s+"\n"+space+"JNZ "+jTextFieldDelayLabel.getText()+"Loop1";
        s=s+"\n"+space+"RET";
        o.jTextAreaAssemblyLanguageEditor.setText(o.jTextAreaAssemblyLanguageEditor.getText()+s);
        o.textEditor.colorEditor();
        return s;
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelaySubroutine(new Assembler()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxDelayChoice;
    private javax.swing.JComboBox jComboBoxReg1;
    private javax.swing.JComboBox jComboBoxReg2;
    private javax.swing.JComboBox jComboBoxReg3;
    private javax.swing.JComboBox jComboBoxRegPair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMaximumDelay;
    private javax.swing.JLabel jLabelMinimumDelay;
    private javax.swing.JTextField jTextFieldDelayLabel;
    private javax.swing.JTextField jTextFieldDelayTime;
    private javax.swing.JTextField jTextFieldTstate;
    // End of variables declaration//GEN-END:variables

}
